### ISSUE TITLE
Ability to generate overview diagram

### ISSUE THREAD

**Issue by garethahealy** [skupperproject/skewer#12]
One thing missing from the examples is a simple overview diagram. There is a lot of text but not much on the visual side, which sometimes makes it hard to remember what is connecting to what.

For example, for [skupper-example-public-to-private](https://github.com/skupperproject/skupper-example-public-to-private)
- k8s cluster `private` connects to k8s cluster `public`

I had a google to see if there were any text to SVG (which there seems to be a few) and obviously, gen-ai came up, one of them being: https://www.eraser.io/diagramgpt

Which generated the below image:

<img width="286" alt="Screenshot 2024-04-10 at 14 51 21" src="https://github.com/skupperproject/skewer/assets/8656974/8d3bea30-491f-4dab-beae-45b079d883de">

Based on the below YAML (notice the **links** key)

```
sites:
  public:
    title: Public
    platform: kubernetes
    namespace: public
  private:
    title: Private
    platform: kubernetes
    namespace: private
    links: [public]
```

The above is to trigger more of a whats possible, than an actual solution suggestion.

gahealy@rh
